### ISSUE TITLE
How to generate the hdf5 data from original data type?

### ISSUE THREAD

**Issue by ChenFeiL** [yulequan/Volumetric-ConvNet-for-prostate-segmentation#4]
Hello,

I've read the paper and the code, but I still don't know how to prepare the ground truth of the data. It'll be very kind of you to help me solve the problem.

**Comment by yulequan** [comment]
Do you know how to make h5 file?

**Comment by gargium** [comment]
Hi all, 

I am also trying to run the code on Caffe. I have downloaded all training and testing data from Promise12, but it is all in MHD and RAW formats. How do you put them in h5 format?

**Comment by yulequan** [comment]
Hi,
I use matlab to prepare the dataset. You can refer this toolbox to read the RAW format.(https://www.mathworks.com/matlabcentral/fileexchange/29344-read-medical-data-3d?focused=5186778&tab=function) 

As for save h5 format, you can use the matlab built-in function "hdf5write"
