### ISSUE TITLE
the data size

### ISSUE THREAD

**Issue by ChenFeiL** [yulequan/Volumetric-ConvNet-for-prostate-segmentation#5]
Hi,
I used matlab to read the H5 files you provided, the data size is 126x99x69, but the size of the MR images is 320×320×60 in you paper "Volumetric ConvNets with Mixed Residual Connections for Automated Prostate Segmentation from 3D MR Images". Can you help me figure out why the data size is different?

Thanks.

**Comment by yulequan** [comment]
1. The 320*320*60 is the average size of one MR images. Different images have different size.
2. When generating the h5 file, we roughly crop the center region of the MR images in order to excluding background regions for better training result.

**Comment by yulequan** [comment]
We normalize them as zero mean and unit variance, that is minus mean and divided by variance.

**Comment by kkhuang1990** [comment]
Another question is about different processes for train and test data. For train, central part with size [126, 99, 69] is extracted from original volume first and subvolume with size [16, 64, 64] is extracted for training, which means train data only contains central parts. However, for test, as you said in your original paper, subvolumes with size [16, 64, 64] and stride [12, 50, 50] is extracted, which means quite a lot of non-central sub-volumes are also extracted. This may cause the problem that train pattern and test pattern may not fit well with each other. What strategies have you chosen to solve this problem

**Comment by yulequan** [comment]
The training data includes two sets: central part and random part from the whole MR images. The second set data can introduce background images into the training dataset.
